version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/kic"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/kic"
