change:
  - head-branch: ['^change/']

enhancement:
  - head-branch: ['^feature/', '^feat/', '^enhancement/', '^enh/']

bug:
  - head-branch: ['^fix/', '^bug/']

chore:
  - head-branch: ['^chore/']

tests:
  - head-branch: ['^tests/', '^test/']

documentation:
  - head-branch: ['^docs/', '^doc/']
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

dependencies:
  - head-branch: ['^deps/', '^dep/', '^dependabot/']
