apiVersion: charts.nginx.org/v1alpha1
kind: NginxIngress
metadata:
  name: nginxingress-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nginx-ingress/values.yaml
  controller:
    defaultTLS:
      secret: ""
    enableCustomResources: true
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: 4.0.0-ubi
    ingressClass:
      name: nginx
    kind: deployment
    nginxplus: true
    mgmt:
      licenseTokenSecretName: "license-token"
    service:
      type: NodePort
  rbac:
    create: true
