name: Create Bundle Approval PR

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version of the operator to submit for approval
        required: true

concurrency:
  group: ${{ github.ref_name }}-create-operator-pr
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e-test:
    name: Run E2E Tests # Deploy NGINX Ingress Operator and Nginx Ingress Controller
    uses: ./.github/workflows/e2e-test.yml

  create-pr:
    name: Certify for Red Hat OpenShift
    runs-on: ubuntu-22.04
    needs: e2e-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Make
        run: |
          make bundle USE_IMAGE_DIGESTS=true

      - name: Checkout certified-operators repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.NGINX_PAT }}
          repository: nginx-bot/certified-operators
          path: certified-operators

      - name: Update certified-operators repo
        working-directory: certified-operators/operators/nginx-ingress-operator
        run: |
          mkdir v${{ inputs.version }}
          cp -R ../../../bundle/manifests v${{ inputs.version }}/
          cp -R ../../../bundle/metadata v${{ inputs.version }}/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: operator nginx-ingress-operator (v${{ inputs.version }})
          commit_author: nginx-bot <integrations@nginx.com>
          commit_user_name: nginx-bot
          commit_user_email: integrations@nginx.com
          create_branch: true
          branch: update-nginx-ingress-operator-to-v${{ inputs.version }}
          repository: certified-operators

      - name: Create PR
        working-directory: certified-operators
        run: |
          gh pr create --title "operator nginx-ingress-operator (v${{ inputs.version }})" --body "Update nginx-ingress-operator to v${{ inputs.version }}" --head nginx-bot:update-nginx-ingress-operator-to-v${{ inputs.version }} --base main --repo redhat-openshift-ecosystem/certified-operators
        env:
          GITHUB_TOKEN: ${{ secrets.NGINX_PAT }}
