name: Delete Operator Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Operator Branch to delete"
        required: true
  push:

permissions:
  contents: read

jobs:
  branch-delete:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.NGINX_PAT }}
          branches: ${{ inputs.branch || 'update-nginx-ingress-operator-to-vpr-221' }}
          repository: certified-operators
          owner: nginx-bot
