name: Delete Operator Branch

on:
  push:
    branches:
      - delete-branch

permissions:
  contents: read

jobs:
  branch-delete:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.NGINX_PAT }}
          branches: update-nginx-ingress-operator-to-v2.2.0
          repository: certified-operators
          owner: nginx-bot
