name: Delete Operator Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Operator Branch to delete"
        default: "update-nginx-ingress-operator-to-v2.3.0"

permissions:
  contents: read

jobs:
  branch-delete:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@d1efac9a6f7a9b408d4e8ff663a99c1fbac17b3f # v3.1.0
        with:
          github_token: ${{ secrets.NGINX_PAT }}
          branches: ${{ inputs.branch }}
          repository: certified-operators
          owner: nginx-bot
