name: Prepare Operator Release

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: "Chart version, e.g. x.y.z"
        type: string
        required: true
      operator_version:
        description: "Operator version, e.g. x.y.z"
        type: string
        required: true
      k8s_version:
        description: "Kubernetes version, e.g. vx.y.z"
        type: string
        required: true
      dry_run:
        description: "Do not commit to a PR"
        type: boolean
        default: false

  workflow_call:
    inputs:
      chart_version:
        description: "Chart version, e.g. x.y.z"
        type: string
        required: true
      operator_version:
        description: "Operator version, e.g. x.y.z"
        type: string
        required: true
      k8s_version:
        description: "Kubernetes version, e.g. vx.y.z"
        type: string
        required: true
      dry_run:
        description: "Do not commit to a PR"
        type: boolean
        default: false  

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Operator
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: nginx/nginx-ingress-helm-operator

      - name: Checkout Kubernetes json schemas
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: nginxinc/kubernetes-json-schema
          path: schemas
          token: ${{ secrets.GITHUB_TOKEN }}
          sparse-checkout: |
            ${{ inputs.k8s_version}}

      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - name: Sync
        id: sync
        run: |
          current_nic_version=$(yq e '.appVersion' helm-charts/nginx-ingress/Chart.yaml)
          echo "Current NIC version: $current_nic_version"

          current_operator_version=$(egrep '^VERSION' Makefile  | awk '{ print $3 }')
          echo "Current Operator version: $current_operator_version"

          echo "Current working directory: $(pwd)"
          ls -l
          echo "Contents of schema directory:"
          ls -l schemas/

          cd helm-charts/
          rm -rf nginx-ingress

          echo "Current working directory after helm-charts: $(pwd)"
          ls -l

          helm pull oci://ghcr.io/nginx/charts/nginx-ingress --untar --version ${{ inputs.chart_version }}
          rm -f nginx-ingress/templates/clusterrole.yaml
          rm -f nginx-ingress/templates/controller-role.yaml
          rm -f nginx-ingress/templates/controller-rolebinding.yaml
          sed -i '14s/name: {{ include "nginx-ingress.fullname" . }}/name: nginx-ingress-operator-nginx-ingress-admin/' nginx-ingress/templates/clusterrolebinding.yaml
          mv ../schemas/${{ inputs.k8s_version }} nginx-ingress/${{ inputs.k8s_version }}
          sed -i -e "s#ref\":.*_def#ref\": \"file://./helm-charts/nginx-ingress/${{ inputs.k8s_version }}/_def#" nginx-ingress/values.schema.json
          rm -rf ../schemas

          echo "Current working directory after removing schema: $(pwd)"
          ls -l
          echo "Contents of parent directory after removing schema:"
          ls -l ../

          new_nic_version=$(yq e '.appVersion' nginx-ingress/Chart.yaml)
          echo "New NIC version: $new_nic_version"

          echo current_nic_version=$current_nic_version >> $GITHUB_OUTPUT
          echo current_operator_version=$current_operator_version >> $GITHUB_OUTPUT
          echo new_nic_version=$new_nic_version >> $GITHUB_OUTPUT
          echo new_operator_version=${{ inputs.operator_version }} >> $GITHUB_OUTPUT

      - name: Find and Replace NIC version
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # v3.0.5
        with:
          find: ${{ steps.sync.outputs.current_nic_version }}
          replace: ${{ steps.sync.outputs.new_nic_version }}
          regex: false
          exclude: .github/**

      - name: Find and Replace Operator version
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # v3.0.5
        with:
          find: ${{ steps.sync.outputs.current_operator_version }}
          replace: ${{ steps.sync.outputs.new_operator_version }}
          regex: false
          exclude: .github/**

      - name: Update bundle files
        run: |
          make bundle
        if: ${{ inputs.dry_run }}

      - name: Run Diff
        run: |
          git diff
        if: ${{ inputs.dry_run }}

      - name: Create Pull Request
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${GITHUB_USERNAME}"
          git config --global user.email "${GITHUB_EMAIL}"

          git checkout -b update-nic-to-${{ steps.sync.outputs.new_nic_version }}
          git add -A
          git commit -m "Update NGINX Ingress Controller to ${{ steps.sync.outputs.new_nic_version }}"
          git push
          gh pr create --title "Update NGINX Ingress Controller to ${{ steps.sync.outputs.new_nic_version }}" --body "This automated PR updates the NGINX Ingress Controller to ${{ steps.sync.outputs.new_nic_version }}.
          The Helm Chart was updated to ${{ inputs.chart_version }}.
          The Operator was updated to ${{ inputs.operator_version }}.
          Kubernetes was updated to ${{ inputs.k8s_version }}."
        if: ${{ ! inputs.dry_run }}
