name: Sync Helm Chart

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: "Chart version"
        required: true
        default: "0.0.0"

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          token: ${{ secrets.NGINX_PAT }}

      - name: Setup Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync
        id: sync
        run: |
          current_version=$(yq e '.appVersion' helm-charts/nginx-ingress/Chart.yaml)
          echo "Current NIC version: $current_version"

          cd helm-charts/
          schema_dir=$(cd nginx-ingress && echo v1.*)
          mv nginx-ingress/$schema_dir $schema_dir
          rm -rf nginx-ingress

          helm pull oci://ghcr.io/nginxinc/charts/nginx-ingress --untar --version ${{ inputs.chart_version }}
          rm -f nginx-ingress/templates/clusterrole.yaml
          rm -f nginx-ingress/templates/controller-role.yaml
          rm -f nginx-ingress/templates/controller-rolebiding.yaml
          sed -i '14s/name: {{ include "nginx-ingress.fullname" . }}/name: nginx-ingress-operator-nginx-ingress-admin/' nginx-ingress/templates/clusterrolebiding.yaml
          mv $schema_dir nginx-ingress/

          new_version=$(yq e '.appVersion' nginx-ingress/Chart.yaml)
          echo "New NIC version: $new_version"

          echo current_version=$current_version >> $GITHUB_OUTPUT
          echo new_version=$new_version >> $GITHUB_OUTPUT

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: ${{ steps.sync.outputs.current_version }}
          replace: ${{ steps.sync.outputs.new_version }}
          regex: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6.0.2
        with:
          token: ${{ secrets.NGINX_PAT }}
          commit-message: Update NGINX Ingress Controller to ${{ steps.sync.outputs.new_version }}
          title: Update NGINX Ingress Controller to ${{ steps.sync.outputs.new_version }}
          branch: feat/update-nic-to-${{ steps.sync.outputs.new_version }}
          author: nginx-bot <integrations@nginx.com>
          body: |
            This automated PR updates the NGINX Ingress Controller to ${{ steps.sync.outputs.new_version }}.
            The Helm Chart was updated to ${{ inputs.chart_version }}.
